[font]
size = 10.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[74;6u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;6u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[78;6u"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[71;6u"
key = "G"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[67;6u"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[66;6u"
key = "B"
mods = "Control|Shift"

[window]
dynamic_title = true
opacity = 0.95

[general]
import = ["/home/mani/.config/alacritty/themes/themes/gotham.toml"]
